// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVcLhm27VY8gHWKwyPZt5riOnaGQpeBd4',
    appId: '1:54434712784:web:da433d6d1adfcd40a9a2d5',
    messagingSenderId: '54434712784',
    projectId: 'flutter-starter-377b4',
    authDomain: 'flutter-starter-377b4.firebaseapp.com',
    storageBucket: 'flutter-starter-377b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ_zGD40qj0HDIIxPg9cy47hwUL9sI-hM',
    appId: '1:54434712784:android:2f219a76e5160446a9a2d5',
    messagingSenderId: '54434712784',
    projectId: 'flutter-starter-377b4',
    storageBucket: 'flutter-starter-377b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDByC6RV-96cEhmciJqYq5peTmEuARXf6A',
    appId: '1:54434712784:ios:e285381e05afe5b1a9a2d5',
    messagingSenderId: '54434712784',
    projectId: 'flutter-starter-377b4',
    storageBucket: 'flutter-starter-377b4.appspot.com',
    iosBundleId: 'com.example.firebasexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDByC6RV-96cEhmciJqYq5peTmEuARXf6A',
    appId: '1:54434712784:ios:a0f7babcd59fa99aa9a2d5',
    messagingSenderId: '54434712784',
    projectId: 'flutter-starter-377b4',
    storageBucket: 'flutter-starter-377b4.appspot.com',
    iosBundleId: 'com.example.firebasexample.RunnerTests',
  );
}
